config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'groups/new'
    get 'groups/index'
    get 'groups/show'
    get 'groups/edit'
    get 'groups/create'
    get 'groups/update'
    get 'groups/destroy'
  end
  # 顧客用
  # URL /members/sign_in ...
  devise_for :members,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :member do
    post "members/guest_sign_in", to: "members/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"
    get "/search", to: "searches#search"
    get 'members/mypage', to: 'members#mypage'
    get "groups/:id/permits" => "groups#permits", as: :permits
    resources :members, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :favorites
      end
    end

    resources :posts, only: [:index, :show, :create, :edit, :update, :destroy]
    resources :free_posts, only: [:index, :show, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource:favorites, only: [:create, :destroy]
    end
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :group_members, only: [:create, :destroy, :update]
    end
  end

  namespace :admin do
    root "members#index" 
    get "/search", to: "searches#search"
    resources :members, only: [:index, :show, :destroy]
    resources :free_posts, only: [:index, :show, :destroy]
    resources :groups, only: [:index, :destroy]
    resources :comments, only: [:destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :free_post
  belongs_to :member

  validates :comment,presence:true,length:{maximum:200}

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :member
  belongs_to :free_post
  
  validates :member_id, uniqueness: {scope: :free_post_id}

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}

end

app/models/free_post.rb
class FreePost < ApplicationRecord
  
  validates :body,presence:true,length:{maximum:200}
  
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}

  belongs_to :member
  belongs_to :group, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image

  def favorited_by?(member)
    favorites.exists?(member_id: member.id)
  end

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  def self.search_for(content, method)
    if method == 'perfect'
      FreePost.where(body: content)
    elsif method == 'forward'
      FreePost.where('body LIKE ?', content + '%')
    elsif method == 'backward'
      FreePost.where('body LIKE ?', '%' + content)
    else
      FreePost.where('body LIKE ?', '%' + content + '%')
    end
  end
    
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :free_posts, dependent: :destroy
  has_many :group_members, dependent: :destroy
  has_one_attached :group_image
  has_many :members, through: :group_members, source: :member
  belongs_to :owner, class_name: "Member"

  validates :name, presence: true
  validates :introduction, presence: true
  
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}

  def self.search_for(content, method)
    if method == 'perfect'
      Group.where(name: content)
    elsif method == 'forward'
      Group.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      Group.where('name LIKE ?', '%' + content)
    else
      Group.where('name LIKE ?', '%' + content + '%')
    end
  end

  def get_group_image
    if group_image.attached?
      group_image
    else
      'no_image.jpg'
    end
  end

  def is_owned_by?(member)
    owner.id == member.id
  end

  def include_member?(member)
    group_members.exists?(member_id: member.id)
  end
  
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  scope :permit, -> { where(status: :permit) }
  scope :application, -> { where(status: :application) }
  scope :rejection, -> { where(status: :rejection) }

  belongs_to :member
  belongs_to :group

  # application=> 申請中
  # permit: 許可済み
  # rejection: 拒否
  enum status: { application: 0, permit: 1, rejection: 2 }
end

app/models/member.rb
class Member < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true      

  has_one_attached :profile_image

  has_many :posts, dependent: :destroy
  has_many :free_posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :group_members, dependent: :destroy
  has_many :groups, through: :group_members
  has_many :favorites, dependent: :destroy
  has_many :favorite_free_posts, through: :favorites, source: :free_post 
  
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}

  GUEST_MEMBER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_MEMBER_EMAIL) do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name = "guest"
      member.introduction = "This is a guest account."
    end
  end
  
  def guest_member?
    email == GUEST_MEMBER_EMAIL
  end

  #退会済みのユーザーを判別
  def active_for_authentication?
    super && (is_active == true)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Member.where(name: content)
    elsif method == 'forward'
      Member.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      Member.where('name LIKE ?', '%' + content)
    else
      Member.where('name LIKE ?', '%' + content + '%')
    end
  end

  def join_group(group)
    self.group_members.find_or_create_by(group: group)
  end

  def reject_group(group)
    self.group_members.find_by(group: group)&.destroy
  end

  def join_group?(group)
    self.groups.include?(group)
  end

  def favorite(free_post)
    self.favorites.find_or_create_by(free_post: free_post)
  end

  def unfavorite(free_post)
    self.favorites.find_by(free_post: free_post)&.destroy
  end

  def favorite?(free_post)
    self.favorite_free_posts.include?(free_post)
  end

  def permit_groups
    Group.joins(:group_members).where(
      'group_members.status': :permit,
      'group_members.member_id': self.id
    ).or(
      Group.where(
        owner_id: self.id
      )
    ).distinct
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :member
  
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  
  validates(:title, {presence: true, length: {maximum: 100}})
  validates(:body, {presence: true, length: {maximum: 300}})

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/free_posts_helper.rb
module Admin::FreePostsHelper
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" style="background-color: #FFE5B4; box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);">
    <div class="container">
      <a class="navbar-brand text-primary fw-bold fs-4" href="/">
        <i class="fa-solid fa-person-running"></i>
        Free and Easy Calorie Control
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_members_path, class: 'nav-link text-dark fw-semibold' do %>
                <i class="fa-solid fa-user"></i> Member
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to admin_free_posts_path, class: 'nav-link text-dark fw-semibold' do %>
                <i class="fa-solid fa-comments"></i> Free Space
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to admin_groups_path, class: 'nav-link text-dark fw-semibold' do %>
                <i class="fa-solid fa-people-group"></i> Group
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to destroy_member_session_path, method: :delete, class: 'nav-link text-danger fw-semibold' do %>
                <i class="fas fa-sign-out-alt"></i> Log Out
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-dark fw-semibold' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_member_registration_path, class: 'nav-link text-success fw-semibold' do %>
                <i class="fas fa-user-plus"></i> Sign Up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_member_session_path, class: 'nav-link text-primary fw-semibold' do %>
                <i class="fas fa-sign-in-alt"></i> Log In
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(obj.errors.count, "error") %> 保存できませんでした。</h4>
    <ul class="mb-0">
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer style="background-color: #FFE5B4; border-top: 1px solid rgba(0, 0, 0, 0.1);" class="text-center py-4">
  <div class="container">
    <p class="mb-1 fw-bold text-primary">Free and Easy Calorie Control</p>
    <p class="mb-0 text-dark">© 2025. All Rights Reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" style="background-color: #FFE5B4; box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);">
    <div class="container">
      <a class="navbar-brand text-primary fw-bold fs-4" href="/">
        <i class="fa-solid fa-person-running"></i>
        Free and Easy Calorie Control
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <% if member_signed_in? %>
            <li class="nav-item">
              <%= link_to members_mypage_path, class: 'nav-link text-dark fw-semibold' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to posts_path, class: 'nav-link text-dark fw-semibold' do %>
                <i class="fa-solid fa-user-tie"></i> My post
              <% end %>
            </li>
            
            <li class="nav-item">
              <%= link_to free_posts_path, class: 'nav-link text-dark fw-semibold' do %>
                <i class="fas fa-users"></i> Free Space
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to favorites_member_path(current_member), class: 'nav-link text-dark fw-semibold' do %>
                <i class="fa-solid fa-heart"></i> Favorites
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to members_path, class: 'nav-link text-dark fw-semibold' do %>
                <i class="fa-solid fa-users-line"></i> Members
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to groups_path, class: 'nav-link text-dark fw-semibold' do %>
                <i class="fa-solid fa-people-group"></i> Groups
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to destroy_member_session_path, method: :delete, class: 'nav-link text-danger fw-semibold' do %>
                <i class="fas fa-sign-out-alt"></i> Log Out
              <% end %>
            </li>
            
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Free_and_easy.soft.calorie_control</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/38ce7d68a2.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/admin_header' %>
    <main>
    <div class="d-flex justify-content-center mb-2">
          <%= render "admin/searches/form" %>
    </div>
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Free_and_easy.soft.calorie_control</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/38ce7d68a2.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <main>
      <!-- Flash Message -->
      <% if flash.now[:notice].present? %>
        <div class="container my-5">
          <div class="alert alert-success">
            <%= flash.now[:notice] %>
          </div>
        </div>
      <% end %>

      <% if flash.now[:error].present? %>
        <div class="container my-5">
          <div class="alert alert-danger">
            <%= flash.now[:error] %>
          </div>
        </div>
      <% end %>

      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>